server:
  port: 8080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: wanted
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 32KB
  data:
    redis:
      connect-timeout: 2s
      timeout: 1s

discord:
  webhookUrl: ${DISCORD_WEBHOOK_URL}



apiKey: ${API_KEY}

jwt:
  access-secret: p3s3WRGpWq6ZIvLoFPCSA3b3oPwJsTY2QfG84zd4EqJrgewLyCIoKeViQ4qX7EHvgqFychb7f3VR4EDqUUWOUw==
  refresh-secret: p3s3WRGpWq6ZIvLoFPCSA3b3oPwJsTY2QfG84zd4EqJrgewLyCIoKeViQ4qX7EHvgqFychb7f3VR4EDqUUWOUw==
  access-token-validity-in-seconds: 30
  refresh-token-validity-in-seconds: 60